name: Release Docker image
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Grab version info
      id: tag
      run: |
        REF=${GITHUB_REF##refs/tags/}
        echo "::set-output name=version::$REF"
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login into ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: charted-dev
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push!
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/charted-dev/qodana-jvm-node:${{steps.tag.outputs.version}}
